version: '3.4'

services:
  consumablemonitor.server:
    image: ${DOCKER_REGISTRY-}consumablemonitorserver
    build:
      context: .
      dockerfile: ConsumableMonitor.Server/Dockerfile
    ports:
      - "5240:80"
  consumablemonitor.database:
    image: postgres:alpine
    volumes:
      - "./data/postgresql:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
