version: '3.4'

services:
  consumablemonitor.server:
    image: ${DOCKER_REGISTRY-}consumablemonitorserver
    build:
      context: .
      dockerfile: ConsumableMonitor.Server/Dockerfile
    ports:
      - "5240:80"
  consumablemonitor.database:
    image: postgres:alpine
    volumes:
      - "./data/postgresql:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: postgrespw
    ports:
      - "5432:5432"
